### ISSUE TITLE
About the Application

### ISSUE THREAD

**Issue by LeeYanQing** [jnbraun/bcnn#1]
Hi, may I know is that any application can apply after run all this codes?

**Comment by jnbraun** [comment]
Hi, the purpose of this library is the training and inference of convolutional neural networks in a general way. As such, it could be used for any traditional computer vision tasks such as object classification or detection. Please refer to example/mnist or example/cifar10 to see simple examples of applications.

The long-term goal of this project is to provide a low-level, efficient and very lightweight deep learning framework to make it easy to deploy in constrained environment (embedded devices for example).
