### ISSUE TITLE
On make I am getting this cblas error.

### ISSUE THREAD

**Issue by assaad** [jnbraun/bcnn#4]
[ 88%] Linking C executable bin/bcnn-cl
/usr/bin/ld: lib/libbcnn.a(bcnn_conv_layer.c.o): in function `bcnn_forward_conv_layer_cpu':
bcnn_conv_layer.c:(.text+0x234f): undefined reference to `cblas_sgemm'
/usr/bin/ld: lib/libbcnn.a(bcnn_conv_layer.c.o): in function `bcnn_backward_conv_layer_cpu':
bcnn_conv_layer.c:(.text+0x26f7): undefined reference to `cblas_sgemm'
/usr/bin/ld: bcnn_conv_layer.c:(.text+0x27e1): undefined reference to `cblas_sgemm'
/usr/bin/ld: bcnn_conv_layer.c:(.text+0x284b): undefined reference to `cblas_sgemm'
/usr/bin/ld: lib/libbcnn.a(bcnn_fc_layer.c.o): in function `bcnn_forward_fullc_layer_cpu':
bcnn_fc_layer.c:(.text+0x9bb): undefined reference to `cblas_sgemm'
/usr/bin/ld: lib/libbcnn.a(bcnn_fc_layer.c.o):bcnn_fc_layer.c:(.text+0xc29): more undefined references to `cblas_sgemm' follow
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/bcnn-cl.dir/build.make:93: bin/bcnn-cl] Error 1
make[1]: *** [CMakeFiles/Makefile2:111: CMakeFiles/bcnn-cl.dir/all] Error 2
make: *** [Makefile:84: all] Error 2

Many thanks!

**Comment by jnbraun** [comment]
Hi, 

It looks like a BLAS linking problem: which BLAS library are you using ?
In general, I would recommend to use OpenBLAS. Depending on your system, you may need to install it yourself. See: https://github.com/xianyi/OpenBLAS and https://github.com/xianyi/OpenBLAS/wiki/Installation-Guide 

Alternatively, you could build without external BLAS dependency by changing in  the CMakeLists.txt: 
`option(USE_BLAS "Build with BLAS library" ON)` to `option(USE_BLAS "Build with BLAS library" OFF)`

Hope it helps
